apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: haproxy-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: registry.hub.docker.com/piscue/haproxy-hateoas
        ports:
        - containerPort: 443
