kind: Service
apiVersion: v1
metadata:
  name: haproxy-lb
spec:
  selector:
    app: haproxy
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
#  clusterIP: 10.0.171.239
#  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#    - ip: 146.148.47.155
